### ISSUE TITLE
error in node module

### ISSUE THREAD

**Issue by PHANTOM-14** [Androz2091/giveaways-bot#68] opened 2020-12-30 06:43 UTC
UnhandledPromiseRejectionWarning: TypeError: member.hasPermission is not a function
    at c:\Users\jains\node_modules\discord-giveaways\src\Giveaway.js:306:82
    at Array.some (<anonymous>)
    at Giveaway.checkWinnerEntry (c:\Users\jains\node_modules\discord-giveaways\src\Giveaway.js:306:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Giveaway.roll (c:\Users\jains\node_modules\discord-giveaways\src\Giveaway.js:340:46)
    at async c:\Users\jains\node_modules\discord-giveaways\src\Giveaway.js:400:29

**Comment by dylanjamesdev** [comment] 2021-01-01 20:38
Same thing here

```[Unhandled Rejection] TypeError: member.hasPermission is not a function
    at /Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:306:82
    at Array.some (<anonymous>)
    at Giveaway.checkWinnerEntry (/Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:306:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Giveaway.roll (/Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:340:46)
    at async /Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:400:29```

**Comment by Androz2091** [comment] 2021-01-03 10:28
Hello, I'm not able to reproduce this bug. Have you modified the code of the bot?

**Comment by PHANTOM-14** [comment] 2021-01-03 10:31
Nah, I just copied the whole code in my bot to test it

**Comment by Androz2091** [comment] 2021-01-03 10:49
And how many winners did you choose? How many people reacted? Do you have GUILD_MEMBERS intent enabled?

**Comment by PHANTOM-14** [comment] 2021-01-03 10:56
Yeah, I have them enabled but if anyone doesn't participate it goes correctly and declares no winner but if anyone participate it crashes the bot and give error.

**Comment by Nico105** [comment] 2021-01-03 11:04
`npm install Androz2091/discord-giveaways#develop` is the fix, with the next release it will be in the master branch

**Comment by PHANTOM-14** [comment] 2021-01-03 11:09
But how to do it in hosting. I mean I need to add it in package.json file. Can you please give in this format `<dependency>: '^version'`

**Comment by Nico105** [comment] 2021-01-03 11:11
Nvm, Androz release a new `discord-giveaways` version with the fix, so just update it `npm update`

**Comment by PHANTOM-14** [comment] 2021-01-03 11:12
Thanks for helping I will look into it in a moment

**Closed** 2021-01-03 14:17 UTC
